project_id = "jk-mlops-dev"
region="us-west1"
zones=["us-west1-a"]
cluster_name_prefix="tff"
client_cluster_count=2
server_cluster_node_count=3
acm_repo_location="https://github.com/jarokaz/tff/"
acm_branch="main"
acm_dir="acm-dir"
